package com.baikal.dao.mapper;

import com.baikal.dao.model.BaikalPushHistory;
import com.baikal.dao.model.BaikalPushHistoryExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BaikalPushHistoryMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_push_history
   *
   * @mbg.generated
   */
  long countByExample(BaikalPushHistoryExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_push_history
   *
   * @mbg.generated
   */
  int deleteByExample(BaikalPushHistoryExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_push_history
   *
   * @mbg.generated
   */
  int insert(BaikalPushHistory record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_push_history
   *
   * @mbg.generated
   */
  int insertSelective(BaikalPushHistory record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_push_history
   *
   * @mbg.generated
   */
  List<BaikalPushHistory> selectByExampleWithBLOBs(BaikalPushHistoryExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_push_history
   *
   * @mbg.generated
   */
  List<BaikalPushHistory> selectByExample(BaikalPushHistoryExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_push_history
   *
   * @mbg.generated
   */
  int updateByExampleSelective(@Param("record") BaikalPushHistory record, @Param("example") BaikalPushHistoryExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_push_history
   *
   * @mbg.generated
   */
  int updateByExampleWithBLOBs(@Param("record") BaikalPushHistory record, @Param("example") BaikalPushHistoryExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_push_history
   *
   * @mbg.generated
   */
  int updateByExample(@Param("record") BaikalPushHistory record, @Param("example") BaikalPushHistoryExample example);
}