package com.baikal.dao.mapper;

import com.baikal.dao.model.BaikalConf;
import com.baikal.dao.model.BaikalConfExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BaikalConfMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_conf
   *
   * @mbg.generated
   */
  long countByExample(BaikalConfExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_conf
   *
   * @mbg.generated
   */
  int deleteByExample(BaikalConfExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_conf
   *
   * @mbg.generated
   */
  int insert(BaikalConf record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_conf
   *
   * @mbg.generated
   */
  int insertSelective(BaikalConf record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_conf
   *
   * @mbg.generated
   */
  int insertSelectiveWithId(BaikalConf record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_conf
   *
   * @mbg.generated
   */
  List<BaikalConf> selectByExample(BaikalConfExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_conf
   *
   * @mbg.generated
   */
  int updateByExampleSelective(@Param("record") BaikalConf record, @Param("example") BaikalConfExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tb_baikal_conf
   *
   * @mbg.generated
   */
  int updateByExample(@Param("record") BaikalConf record, @Param("example") BaikalConfExample example);
}