package com.baikal.dao.mapper;

import com.baikal.dao.model.BaikalBase;
import com.baikal.dao.model.BaikalBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaikalBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_baikal_base
     *
     * @mbg.generated
     */
    long countByExample(BaikalBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_baikal_base
     *
     * @mbg.generated
     */
    int deleteByExample(BaikalBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_baikal_base
     *
     * @mbg.generated
     */
    int insert(BaikalBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_baikal_base
     *
     * @mbg.generated
     */
    int insertSelective(BaikalBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_baikal_base
     *
     * @mbg.generated
     */
    int insertSelectiveWithId(BaikalBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_baikal_base
     *
     * @mbg.generated
     */
    List<BaikalBase> selectByExample(BaikalBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_baikal_base
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BaikalBase record, @Param("example") BaikalBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_baikal_base
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BaikalBase record, @Param("example") BaikalBaseExample example);
}